name: dissertation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - snakemake-minimal>=5.20.1
  - pandas>=1.4
  - matplotlib-base
  - hvplot
  - scipy
  - seaborn
  - ficus
  - sourmash
  - jupyterlab
  - nb_conda_kernels
  - taxonomy
  - pip
  - pip:
    - cmdbench
