name: CI

on: [push]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/dissertation

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1

    - name: install xelatex
      run: sudo apt install -y texlive-xetex texlive-science

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: dissertation
          use-mamba: true
          auto-activate-base: false

    - name: Cache main conda environment
      uses: actions/cache@v2
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
      id: cache

    - name: Update environment
      run: mamba env update -n dissertation -f environment.yml
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Cache snakemake conda environments
      uses: actions/cache@v2
      with:
        path: .snakemake/conda
        key: ${{ matrix.label }}-snakemake-conda-${{ hashFiles('envs/R.yml') }}-${{ env.CACHE_NUMBER }}

    - name: Install aggiedown in R environment
      run: |
        export PATH="/usr/share/miniconda3/bin:$PATH"
        source activate dissertation
        snakemake -j 1 --use-conda --conda-frontend mamba install_deps
      env:
        GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}

    - name: Cache manubot citeproc requests
      uses: actions/cache@v2
      with:
        path: |
          index/_book/cache/requests-cache.sqlite
        key: ${{ matrix.label }}-manubot-${{ hashFiles('index/_book/cache/references-cache.json') }}-${{ env.CACHE_NUMBER }}

    - name: Run pipeline
      run: |
        export PATH="/usr/share/miniconda3/bin:$PATH"
        source activate dissertation
        snakemake -j 1 --use-conda --conda-frontend mamba
    - name: upload PDF to GH artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dissertation.pdf
        path: index/_book/dissertation.pdf

    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GHR_PATH: index/_book/dissertation.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
